'use client';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './Header/Header';
import { NextUIProvider } from '@nextui-org/react';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <Header />
        </NextUIProvider>
        <div className="container mx-auto p-12 h-screen">{children}</div>
      </body>
    </html>
  );
}
